---
- name: Import setup tasks.
  ansible.builtin.import_tasks: setup.yml

- name: Import storage tasks.
  ansible.builtin.import_tasks: storage.yml

- name: Run tasks under user {{ nc_user }}.
  become: true
  become_user: "{{ nc_user }}"
  block:
    - name: Import network tasks.
      ansible.builtin.import_tasks: network.yml

    - name: Import db tasks.
      ansible.builtin.import_tasks: db.yml

    - name: Import app tasks.
      ansible.builtin.import_tasks: app.yml

    - name: Import cron tasks.
      ansible.builtin.import_tasks: cron.yml
