---
- name: Check if user has lingering enabled.
  ansible.builtin.command:
    cmd: "ls /var/lib/systemd/linger"
  changed_when: false
  register: linger

- name: Enable linger for user {{ nc_user }}
  become: true
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ nc_user }}"
  changed_when: true
  when: "nc_user not in linger.stdout"
