---
- name: Ensure app volume directories exist.
  become: true
  ansible.builtin.file:
    path: "{{ nc_volumes_dir }}/{{ item.dir }}"
    owner: 100032
    group: 100032
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - { dir: "app", mode: "755"}
    - { dir: "config", mode: "755"}
    - { dir: "data", mode: "770"}
