---
- name: Converge
  hosts: all

  vars_files:
    - vars/nginx.yml
    - vars/nc.yml
    - vars/proxy.yml

  tasks:
    - name: "Include palekiwi.nc"
      ansible.builtin.include_role:
        name: "palekiwi.nc"

    - name: Ensure a https conf template is installed.
      ansible.builtin.template:
        src: templates/nginx/https.conf.j2
        dest: "{{ nc_proxy_path }}/{{ nc_proxy_server_name }}.conf"
        mode: "0644"
        owner: "{{ nc_user }}"
        group: "{{ nc_user }}"
        setype: container_file_t

    - name: Restart nginx-container.
      containers.podman.podman_container_exec:
        name: nginx-container
        command: "nginx -s reload"
