---
nc_user: vagrant
nc_net_name: nc

nc_pod_name: nc
nc_container_name: nc-container

nc_http_port: 8080

# images
nc_image_name: "docker.io/library/nextcloud"
nc_image_tag: "latest"

# directories
nc_volumes_dir: "/mnt/nc"

# env vars: NEXTCLOUD
nc_env_admin_user: admin
nc_env_admin_password: nextcloud
nc_env_overwriteprotocol: ""
nc_env_overwritecliurl: ""
nc_env_trusted_domains: "{{ ansible_host }}"

# database vars
nc_db_host: "{{ mariadb_pod_name }}"
nc_db_user: "{{ mariadb_db_user }}"
nc_db_database: "{{ mariadb_db_database }}"
nc_db_password: "{{ mariadb_db_password }}"
