---
- name: Prepare
  hosts: all

  vars_files:
    - vars/db.yml
    - vars/nc.yml

  tasks:
    - name: Include epel role.
      ansible.builtin.include_role:
        name: palekiwi.epel

    - name: Ensure podman is installed.
      become: true
      ansible.builtin.dnf:
        name: podman
        state: present

    - name: Ensure required volume dirs exist for db.
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0755"
        owner: vagrant
        group: vagrant
        state: directory
        setype: container_file_t
      loop:
        - "{{ mariadb_volumes_dir }}"

    - name: Include mariadb role.
      ansible.builtin.include_role:
        name: palekiwi.mariadb
